const now = new Date('2026-05-12T10:30:00.000Z')

function iso(minutesAgo) {
  return new Date(now.getTime() - minutesAgo * 60_000).toISOString()
}

export const sampleLeads = [
  {
    id: 'lead_lumora',
    date: '2026-05-12',
    region: 'Poland',
    industry: 'Hospitality',
    companyName: 'Lumora Bistro',
    companyLinkedInUrl: 'https://www.linkedin.com/company/lumora-bistro',
    employeeLinkedInUrl: 'https://www.linkedin.com/in/marta-kowalska',
    websiteDomainName: 'lumorabistro.pl',
    emailDomainName: 'lumorabistro.pl',
    status: 'Uploaded',
    owner: 'Ava Patel',
    disqualificationCategory: null,
    lowEffortResults: [],
    manualChecks: {
      duplicateCheck: false,
      internalOwnership: false,
      industryValidation: false,
      previousDisqualification: false,
      tagEnrichment: false,
    },
    manualNotes: '',
    validationHistory: [
      {
        id: 'audit_lumora_1',
        actor: 'Ava Patel',
        action: 'Lead uploaded',
        timestamp: iso(310),
      },
    ],
    processingTimeMinutes: 18,
    slaHours: 18,
    createdAt: iso(310),
  },
  {
    id: 'lead_nordlane',
    date: '2026-05-11',
    region: 'Czechia',
    industry: 'Retail',
    companyName: 'Nordlane Outfitters',
    companyLinkedInUrl: 'https://www.linkedin.com/company/nordlane-outfitters',
    employeeLinkedInUrl: 'https://www.linkedin.com/in/jakub-novak',
    websiteDomainName: 'nordlane.cz',
    emailDomainName: 'nordlane.cz',
    status: 'Low Effort Validation Passed',
    owner: 'Mila Reyes',
    disqualificationCategory: null,
    lowEffortResults: [
      {
        id: 'val_nordlane_website',
        type: 'Company website',
        result: 'Pass',
        confidence: 94,
        reasoning: 'Website responds with SSL and localized commerce content.',
        details: ['HTTPS available', 'Live product pages', 'Domain matches email domain'],
      },
      {
        id: 'val_nordlane_business',
        type: 'Business type',
        result: 'Pass',
        confidence: 88,
        reasoning: 'Independent retail business with no enterprise-chain signal.',
        details: ['SMB footprint', 'No marketplace aggregation', 'Consistent brand mentions'],
      },
      {
        id: 'val_nordlane_social',
        type: 'Social presence',
        result: 'Pass',
        confidence: 82,
        reasoning: 'LinkedIn, Instagram, and Google Business-style signals were validated.',
        details: ['LinkedIn active', 'Google Business probable', 'Instagram checked'],
      },
    ],
    manualChecks: {
      duplicateCheck: false,
      internalOwnership: false,
      industryValidation: false,
      previousDisqualification: false,
      tagEnrichment: false,
    },
    manualNotes: '',
    validationHistory: [
      {
        id: 'audit_nordlane_1',
        actor: 'AI Validator',
        action: 'Low effort validation passed',
        timestamp: iso(240),
      },
    ],
    processingTimeMinutes: 42,
    slaHours: 18,
    createdAt: iso(260),
  },
  {
    id: 'lead_solaris',
    date: '2026-05-10',
    region: 'Germany',
    industry: 'Energy',
    companyName: 'Solaris Field Services',
    companyLinkedInUrl: 'https://www.linkedin.com/company/solaris-field-services',
    employeeLinkedInUrl: 'https://www.linkedin.com/in/lea-schneider',
    websiteDomainName: 'solaris-field.de',
    emailDomainName: 'solaris-field.de',
    status: 'Enrichment Complete',
    owner: 'Noah Kim',
    disqualificationCategory: null,
    lowEffortResults: [
      {
        id: 'val_solaris_website',
        type: 'Company website',
        result: 'Pass',
        confidence: 96,
        reasoning: 'Live website with valid SSL and company-specific service pages.',
        details: ['SSL valid', 'Localized German pages', 'Contact page detected'],
      },
      {
        id: 'val_solaris_location',
        type: 'Location & language match',
        result: 'Pass',
        confidence: 91,
        reasoning: 'Website language and service region align with Germany.',
        details: ['German language', 'Regional phone prefix', 'Office city present'],
      },
    ],
    manualChecks: {
      duplicateCheck: true,
      internalOwnership: true,
      industryValidation: true,
      previousDisqualification: true,
      tagEnrichment: true,
    },
    manualNotes: 'Good fit. No previous disqualification and ownership clear.',
    validationHistory: [
      {
        id: 'audit_solaris_1',
        actor: 'AI Validator',
        action: 'Low effort validation passed',
        timestamp: iso(210),
      },
      {
        id: 'audit_solaris_2',
        actor: 'Noah Kim',
        action: 'Manual validation approved',
        timestamp: iso(190),
        note: 'Industry and ICP match confirmed.',
      },
      {
        id: 'audit_solaris_3',
        actor: 'AI Enrichment',
        action: 'Enrichment completed',
        timestamp: iso(140),
      },
    ],
    enrichment: {
      keyDecisionMakerName: 'Lea Schneider',
      position: 'Head of Field Operations',
      emailAddress: 'lea.schneider@solaris-field.de',
      phoneNumber: '+49 30 5550 1842',
      confidenceScore: 91,
      completedAt: iso(140),
      additionalContacts: [
        {
          id: 'contact_solaris_1',
          name: 'Tobias Keller',
          title: 'Commercial Director',
          email: 't.keller@solaris-field.de',
          phone: '+49 30 5550 1847',
          confidence: 84,
          source: 'LinkedIn + domain pattern',
        },
        {
          id: 'contact_solaris_2',
          name: 'Nina Hartmann',
          title: 'Regional Manager',
          email: 'nina.hartmann@solaris-field.de',
          phone: 'No information found',
          confidence: 78,
          source: 'Company directory',
        },
      ],
    },
    processingTimeMinutes: 96,
    slaHours: 18,
    createdAt: iso(2600),
  },
  {
    id: 'lead_carrefour',
    date: '2026-05-09',
    region: 'France',
    industry: 'Retail',
    companyName: 'Carrefour Montmartre',
    companyLinkedInUrl: 'https://www.linkedin.com/company/carrefour',
    employeeLinkedInUrl: 'https://www.linkedin.com/in/sample-contact',
    websiteDomainName: 'carrefour.fr',
    emailDomainName: 'carrefour.com',
    status: 'Low Effort Validation Failed',
    owner: 'Iris Chen',
    disqualificationCategory: 'DQ',
    lowEffortResults: [
      {
        id: 'val_carrefour_enterprise',
        type: 'Too-big enterprise detection',
        result: 'Fail',
        confidence: 99,
        reasoning: 'LLM matched Carrefour as an obvious too-big enterprise chain and stopped the workflow.',
        details: ['Enterprise list match', 'Examples include Česká Pošta, Żabka, Carrefour', 'Stop immediately as DQ'],
      },
    ],
    manualChecks: {
      duplicateCheck: false,
      internalOwnership: false,
      industryValidation: false,
      previousDisqualification: false,
      tagEnrichment: false,
    },
    manualNotes: '',
    validationHistory: [
      {
        id: 'audit_carrefour_1',
        actor: 'AI Validator',
        action: 'Low effort validation failed',
        timestamp: iso(880),
        note: 'DQ: enterprise chain.',
      },
    ],
    processingTimeMinutes: 12,
    slaHours: 18,
    createdAt: iso(900),
  },
]
